spring:
    application:
        name: Gateway Micro service
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        open-in-view: true
    datasource:
        url: jdbc:postgresql://localhost:5432/card_game
        username: sa
        password: sa
        driver-class-name: org.postgresql.Driver

server:
    port: 8011

eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true