version: "3.8"

services:
    card-db:
        container_name: card-db
        image: card-db
        build: ./dock-db
        ports:
            - "5432:5432"
        volumes:
            - card-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: sa
            POSTGRES_DB: card_game
    pg-admin:
        container_name: pg-admin
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.fr
            PGADMIN_DEFAULT_PASSWORD: test

volumes:
    card-db-data:
        external: false
