services:
    pg-admin:
        container_name: pg-admin
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.fr
            PGADMIN_DEFAULT_PASSWORD: test
        networks:
            - api-db-network
