version: "3.8"

services:
  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - DISCOVERY_URL=http://discovery:8761

  # SERVICES
  card:
    build:
      context: ./card-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  store:
    build:
      context: ./store-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  # API GATEWAY
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
      - card
      - store
      - user
    depends_on:
      - discovery