spring:
  application:
    name: CardForge
  datasource:
    name: CardForge
    url: jdbc:h2:mem:my_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect