spring:
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        open-in-view: true
    datasource:
        url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
        username: sa
        password: sa
        driver-class-name: org.postgresql.Driver
