spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: admin

server:
  port: 8013

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

gateway:
  url: http://localhost:8011