INSERT INTO Card (name, description, family, affinity, image_url, miniature_url, energy, health, attack, defence) VALUES
('Fire Dragon', 'A fierce dragon with fiery breath', 'Dragon', 'Fire', 'fire_dragon.png', 'fire_dragon_mini.png', 10, 100, 50, 30),
('Water Spirit', 'A spirit born from water', 'Elemental', 'Water', 'water_spirit.png', 'water_spirit_mini.png', 5, 80, 20, 10),
('Earth Golem', 'A golem made of solid earth', 'Golem', 'Earth', 'earth_golem.png', 'earth_golem_mini.png', 8, 150, 40, 50),
('Wind Fairy', 'A swift fairy that controls the wind', 'Fairy', 'Wind', 'wind_fairy.png', 'wind_fairy_mini.png', 3, 60, 30, 20),
('Thunder Beast', 'A beast that harnesses the power of thunder', 'Beast', 'Thunder', 'thunder_beast.png', 'thunder_beast_mini.png', 12, 120, 60, 40),
('Shadow Assassin', 'A silent assassin from the shadows', 'Assassin', 'Dark', 'shadow_assassin.png', 'shadow_assassin_mini.png', 4, 70, 90, 20),
('Light Guardian', 'A guardian blessed by light', 'Guardian', 'Light', 'light_guardian.png', 'light_guardian_mini.png', 9, 130, 70, 60),
('Forest Elf', 'An elf who protects the forest', 'Elf', 'Nature', 'forest_elf.png', 'forest_elf_mini.png', 2, 50, 15, 10),
('Ice Wizard', 'A wizard who masters ice spells', 'Wizard', 'Ice', 'ice_wizard.png', 'ice_wizard_mini.png', 7, 90, 25, 35),
('Fire Phoenix', 'A mythical phoenix reborn from flames', 'Phoenix', 'Fire', 'fire_phoenix.png', 'fire_phoenix_mini.png', 15, 200, 100, 80),
('Ocean Mermaid', 'A mermaid with enchanting voice', 'Mermaid', 'Water', 'ocean_mermaid.png', 'ocean_mermaid_mini.png', 6, 70, 20, 15),
('Rock Titan', 'A giant titan made of rock', 'Titan', 'Earth', 'rock_titan.png', 'rock_titan_mini.png', 11, 180, 50, 70),
('Sky Griffin', 'A majestic griffin that soars the sky', 'Griffin', 'Wind', 'sky_griffin.png', 'sky_griffin_mini.png', 5, 110, 60, 50),
('Electric Wolf', 'A wolf with electric powers', 'Wolf', 'Thunder', 'electric_wolf.png', 'electric_wolf_mini.png', 8, 90, 45, 40),
('Dark Knight', 'A knight with a dark past', 'Knight', 'Dark', 'dark_knight.png', 'dark_knight_mini.png', 10, 140, 80, 60),
('Holy Paladin', 'A paladin blessed with holy light', 'Paladin', 'Light', 'holy_paladin.png', 'holy_paladin_mini.png', 12, 160, 85, 70),
('Jungle Hunter', 'A hunter lurking in the jungle', 'Hunter', 'Nature', 'jungle_hunter.png', 'jungle_hunter_mini.png', 4, 60, 25, 15),
('Frost Giant', 'A giant from the frost lands', 'Giant', 'Ice', 'frost_giant.png', 'frost_giant_mini.png', 9, 170, 55, 65),
('Inferno Dragon', 'A dragon from the depths of hell', 'Dragon', 'Fire', 'inferno_dragon.png', 'inferno_dragon_mini.png', 14, 190, 95, 75),
('Sea Serpent', 'A serpent that rules the sea', 'Serpent', 'Water', 'sea_serpent.png', 'sea_serpent_mini.png', 7, 100, 30, 25),
('Mountain Giant', 'A giant born from the mountains', 'Giant', 'Earth', 'mountain_giant.png', 'mountain_giant_mini.png', 10, 160, 60, 70),
('Wind Spirit', 'A spirit that controls the wind', 'Elemental', 'Wind', 'wind_spirit.png', 'wind_spirit_mini.png', 4, 50, 20, 10),
('Thunder Eagle', 'An eagle that commands thunder', 'Eagle', 'Thunder', 'thunder_eagle.png', 'thunder_eagle_mini.png', 11, 120, 70, 60),
('Dark Sorcerer', 'A sorcerer with dark magic', 'Sorcerer', 'Dark', 'dark_sorcerer.png', 'dark_sorcerer_mini.png', 8, 90, 60, 40),
('Light Mage', 'A mage with powers of light', 'Mage', 'Light', 'light_mage.png', 'light_mage_mini.png', 9, 130, 75, 50),
('Nature Druid', 'A druid connected to nature', 'Druid', 'Nature', 'nature_druid.png', 'nature_druid_mini.png', 5, 70, 25, 20),
('Ice Dragon', 'A dragon that breathes ice', 'Dragon', 'Ice', 'ice_dragon.png', 'ice_dragon_mini.png', 13, 180, 90, 80),
('Flame Warrior', 'A warrior engulfed in flames', 'Warrior', 'Fire', 'flame_warrior.png', 'flame_warrior_mini.png', 6, 90, 40, 30),
('Aqua Mage', 'A mage with water spells', 'Mage', 'Water', 'aqua_mage.png', 'aqua_mage_mini.png', 5, 60, 25, 20),
('Stone Golem', 'A golem carved from stone', 'Golem', 'Earth', 'stone_golem.png', 'stone_golem_mini.png', 7, 140, 50, 60),
('Storm Hawk', 'A hawk that brings storms', 'Hawk', 'Wind', 'storm_hawk.png', 'storm_hawk_mini.png', 8, 100, 45, 35),
('Lightning Tiger', 'A tiger with lightning speed', 'Tiger', 'Thunder', 'lightning_tiger.png', 'lightning_tiger_mini.png', 9, 110, 55, 40),
('Shadow Warrior', 'A warrior from the shadows', 'Warrior', 'Dark', 'shadow_warrior.png', 'shadow_warrior_mini.png', 6, 80, 60, 30),
('Holy Priest', 'A priest with holy powers', 'Priest', 'Light', 'holy_priest.png', 'holy_priest_mini.png', 10, 140, 65, 50),
('Forest Guardian', 'A guardian of the forest', 'Guardian', 'Nature', 'forest_guardian.png', 'forest_guardian_mini.png', 7, 90, 35, 40),
('Glacial Titan', 'A titan from the glaciers', 'Titan', 'Ice', 'glacial_titan.png', 'glacial_titan_mini.png', 12, 170, 75, 70);

INSERT INTO kuser (first_name, last_name, user_name, email_address, password, wallet, role) 
values('sa', 'sa', 'admin', 'sa@sa.fr', 'admin', '1.0', 'ADMIN');
